### ISSUE TITLE
Add Voice Recognition

### ISSUE THREAD

**Issue by timstableford** [timstableford/P-BrainAndroid#1]
Voice recognition needs to added. Initial experiments show PocketSphinx has trouble picking up key words and has very low accuracy. It may be necessary to use Google voice libraries and have a button for listening.

**Comment by patrickjquinn** [comment]
Are you using any models with this? i.e the wikipedia based language model and dictionary? or are you just using PocketSphinx raw?

**Comment by timstableford** [comment]
I'm just using a modified version of the Android demo they released. It comes with a model and dictionary but I suspect a wikipedia based one would be better. What I'm currently finding while experimenting with key phrase detection is that it's pretty good at picking up when I say the key phrase but has many false positives.

**Comment by patrickjquinn** [comment]
Is there any concept of a confidence threshold in PocketSphinx? And yep maybe try another prebuilt model if you can find a decent one?

**Comment by timstableford** [comment]
I haven't looked deeply into it, but it seems on some callbacks it returns a confidence score as an int. This has always been 0 in my testing.

**Comment by timstableford** [comment]
I've found a library just for hotword detection, Snowboy. It's pretty damn good. It might even be worth using it on other platforms. The only downside is that each keyphrase needs to be trained, which I can add an option to do in app. For default though, we will need to improve the "Brain" model on their site - https://snowboy.kitt.ai/dashboard

**Comment by patrickjquinn** [comment]
Yep! Thats what the RasPi Client uses https://github.com/patrickjquinn/P-Brain.ai-RasPi

There is a pretrained hot-word model in the resources folder of that repo if you want it!

**Comment by timstableford** [comment]
Not sure if I have their naming conventions right, but pmdl is a personal model and umdl is a universal model right? Shouldn't we be using the universal one? :+1:

**Comment by patrickjquinn** [comment]
That makes a ton of sense... I was only testing and training it against my own voice, i'm going to give the universal model a try now.

**Comment by patrickjquinn** [comment]
Hotword detection works, however the speech recognition portion doesnt seem to yet, is that correct?

**Comment by timstableford** [comment]
It didn't until just now. Speech recognition works, TTS works and keyword training works.
