### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by paramjit1992singh** [timstableford/P-BrainAndroid#10]
not able to login, into the app

in connection setting gave server address as http://192.168.2.4:4567
username : admin
password : admin

Please tell the steps on how to run the app

**Comment by timstableford** [comment]
Hi @paramjit1992singh I'm going to need a bit more detail. Do you have a P-Brain server running at that address you listed? Is the server and phone on the same network (wifi on?)? If both of those are true would you append the output of 'adb logcat' to this issue please?
