### ISSUE TITLE
Add Text To Speech

### ISSUE THREAD

**Issue by timstableford** [timstableford/P-BrainAndroid#2]
Add text to speech on responses, handling the silent flag too. Probably using Google API's.

**Comment by patrickjquinn** [comment]
The native Android one should be able to handle this, something like 

```
public static void speakResponse(String response) {
     TextToSpeech tts = new TextToSpeech(MainActivity.this, null);
     tts.setLanguage(Locale.US);
     tts.speak(response, TextToSpeech.QUEUE_ADD, null);
}
```

**Comment by timstableford** [comment]
Yeah, that's what I was thinking of. I wanted to explore open source alternatives first but I don't think I'll find anything as good.

**Comment by timstableford** [comment]
Now implemented.
