### ISSUE TITLE
Improve Training Activity Aesthetics

### ISSUE THREAD

**Issue by timstableford** [timstableford/P-BrainAndroid#5]
The training activity is not intuitive and could be a lot better looking.

**Comment by patrickjquinn** [comment]
I dont know if you have access to Google Assistant, but i've been building the P-Brain iOS client (due for open sourcing today) using that as the template. It also has hot word training so you might want to look into that for some inspiration?

**Comment by timstableford** [comment]
I had something in mind for the training screen that I thought would work well. Updated it now. Let me know if there's any improvements you think I could make :+1:
