### ISSUE TITLE
Crashing at runtime

### ISSUE THREAD

**Issue by patrickjquinn** [timstableford/P-BrainAndroid#7]
Just noticed `Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference` occurring at runtime with v2, error is occurring in 
```
private void setupSocket(String server) {
        if (!connectedServer.equals(server) || mSocket == null) {
            teardownSocket();
            try {
                mSocket = IO.socket(server);
                setupSocketListeners();
                connectedServer = server;
                mSocket.connect();
            } catch (URISyntaxException e) {
                Log.e(TAG, "Error connecting socket.io.", e);
                statusMessage(getString(R.string.server_not_connected));
            }
        }
    }
```

of the MainActivity.java

on this `if (!connectedServer.equals(server) || mSocket == null) {` line (Line 265)

That said my device is API 25 (i.e Nougat) so maybe it is something related to that.

**Comment by timstableford** [comment]
Fair point, connectedServer would be null. I hadn't actually tested the refactoring yet, that'll probably be done tomorrow morning and then a stable release this weekend.

**Comment by timstableford** [comment]
Now resolved.
