### ISSUE TITLE
Training hotword throws error

### ISSUE THREAD

**Issue by patrickjquinn** [timstableford/P-BrainAndroid#8]
When in the training screen, upon pressing the train button the network request (whilst uploading the samples) fails.

The error is `{"name":["This field may not be blank."]}` and it seems to be stemming from `obj.put("name", name);` with name being `null`, in `TrainActivity.java`

I've tried hardcoding `name` to be an arbitrary static value to no effect, is it being passed into the query when it needs to be in the headers or vice versa?

**Comment by timstableford** [comment]
This works on Android 6.0 and 4.4. Does the first message on the training screen say your assistants name or does it say 'null'?

**Comment by patrickjquinn** [comment]
`While holding the microphone say "` so yep looks like its null!

**Comment by timstableford** [comment]
This definitely isn't a null name issue. It seems to be that the name is a 0 length string. Is your server sending a name through the set_name socket command?

**Comment by timstableford** [comment]
(or is the name right in config/name.json)

**Comment by patrickjquinn** [comment]
AH! Name is `name:""` in the name.json file. My bad!

**Comment by timstableford** [comment]
Hmm, we should probably add server side checks for that and possibly client side too.

**Comment by patrickjquinn** [comment]
Yep if the value is empty then prompt the client to enter a name value perhaps?

**Comment by timstableford** [comment]
Theoretically it should never be empty in the first place. There's a default of 'Brain' after all. If it was set to a zero length string then something went wrong parsing the query. I suspect it picked up a "your name is" with no name. So I'm not going to go that far with client side fixes, I'll just present a warning if it's detected.
